version: '3'
services:
  db:
    image: postgres:16.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: admin_mailing_service_db

  backend:
    build:
      context: .
    expose:
      - 8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn admin_mailing.wsgi -b 0.0.0.0:8080
      "
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8000:80
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume: