# Generated by Django 4.2.8 on 2023-12-13 11:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате 7XXXXXXXXXX', regex='^7\\d{10}$')])),
                ('operator_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Код мобильного оператора должен состоять из трех цифр', regex='^\\d{3}$')])),
                ('tag', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='time_zone должен быть в формате GMT+XX', regex='^GMT\\+\\d{2}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('uu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('tag_filter', models.CharField(blank=True, max_length=50)),
                ('operator_code_filter', models.CharField(blank=True, max_length=3)),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('send_status', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.client')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dispatch')),
            ],
        ),
    ]
